"""Adding size field to db

Revision ID: 9299025584db
Revises: 470bbf654408
Create Date: 2016-06-01 16:40:30.035195

"""

# revision identifiers, used by Alembic.
revision = '9299025584db'
down_revision = '470bbf654408'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('size', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'size')
    ### end Alembic commands ###
