language: python
python:
    - "2.7"
services:
    - redis-server
cache: pip
install:
    - pip install -r requirements/dev.txt
script: cd app && nosetests -v --cover-package=underground_garage --with-xcoverage
after_success:
    - coveralls
