version: '2'

services:
  redis:
    restart: "always"
    image: redis:3.2-alpine
    env_file:
      - ./common.env

  postgres:
    restart: "always"
    image: postgres:9.5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - ./common.env

  web:
    restart: "always"
    build: ./app
    expose:
      - "8000"
    ports:
    - "8000:8000"
    links:
      - redis:redis
      - postgres:postgres
    command: "python /usr/src/app/manage.py runserver -d -r -p 8000 --host=0.0.0.0" #"gunicorn --log-level debug -w 2 -b :8000 wsgi:app"
    volumes:
      - ./data/google_key:/google_key
      - ./app:/usr/src/app
      - ./k8s/google:/google/google
    env_file:
      - ./common.env

  celery:
    restart: "always"
    build: ./app
    links:
      - redis:redis
      - postgres:postgres
    command: "celery worker -A celery_worker.celery -l info"
    volumes:
      - ./data/google_key:/google_key
      - ./k8s/google:/google/google
    env_file:
      - ./common.env
  
  celery-beat:
    restart: "always"
    build: ./app
    links:
      - redis:redis
      - postgres:postgres
    command: "celery beat -A celery_worker.celery -l info"
    volumes:
      - ./data/google_key:/google_key
      - ./k8s/google:/google/google
    env_file:
      - ./common.env

  nginx:
    restart: "always"
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web:underground-web

  #flower:
  #  image: placr/flower
  #  env_file:
  #    - ./common.env
  #  links:
  #    - redis:redis
