apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: underground
    name: underground-web
    service: web
    tier: frontend
  name: underground-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: underground
        name: underground-web
        service: web
        tier: frontend
    spec:
      containers:
      - command:
        - gunicorn
        - --log-level
        - debug
        - -w
        - '2'
        - -b
        - :8000
        - wsgi:app
        env:
        - name: UNDERGROUND_CONFIG
          value: production
        - name: UNDERGROUND_DB
          valueFrom:
            secretKeyRef:
              key: underground-db
              name: underground-secrets
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              key: celery-broker-url
              name: underground-config
        - name: SHOWS_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              key: shows-redis-host
              name: underground-config
        - name: SHOWS_REDIS_DB
          valueFrom:
            configMapKeyRef:
              key: shows-redis-db
              name: underground-config
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              key: sentry-dsn
              name: underground-secrets
        - name: GOOGLE_JSON_PATH
          valueFrom:
            secretKeyRef:
              key: google-json-path
              name: underground-secrets
        - name: GOOGLE_PROJECT
          valueFrom:
            secretKeyRef:
              key: google-project
              name: underground-secrets
        - name: STORAGE_PROVIDER
          valueFrom:
            secretKeyRef:
              key: storage-provider
              name: underground-secrets
        - name: STORAGE_KEY
          valueFrom:
            secretKeyRef:
              key: storage-key
              name: underground-secrets
        - name: STORAGE_SECRET
          valueFrom:
            secretKeyRef:
              key: storage-secret
              name: underground-secrets
        - name: STORAGE_CONTAINER
          valueFrom:
            secretKeyRef:
              key: storage-container
              name: underground-secrets
        image: gcr.io/alex-kerney/underground:0.7.11
        name: web
        ports:
        - containerPort: 8000
          name: gunicorn
        resources:
          limits:
            cpu: 400m
          requests:
            cpu: 10m
        volumeMounts:
        - mountPath: /google
          name: google-config
          readOnly: true
      volumes:
      - name: google-config
        secret:
          secretName: underground-service-account
